# Generated by Django 5.0 on 2024-05-11 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_delete_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 11), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='task',
            name='website_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
