# Generated by Django 5.0 on 2024-05-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='date_is_here',
        ),
    ]
